cart/urls.py
from django.urls import path

from cart.apps import CartConfig
from cart.view.API_cart import CartListAPIView, CartCreateAPIView, CartDeleteAPIView, CartUpdateAPIView, \
    CartCleanAPIView, CartInfoAPIView
from cart.view.cart import CartListView, product_add_cart, change_qty_cart, clean_cart, product_delete_cart

app_name = CartConfig.name

urlpatterns = [
    # Cart
    path('', CartListView.as_view(), name='home'),
    path('create/<int:pk>/', product_add_cart, name='product_add_cart'),
    path('change/<int:pk>/', change_qty_cart, name='change_qty_cart'),
    path('clean/', clean_cart, name='clean_cart'),
    path('delete/<int:pk>/', product_delete_cart, name='product_delete_cart'),

    # API Cart
    path('API/', CartListAPIView.as_view()),
    path('API/create/', CartCreateAPIView.as_view()),
    path('API/update/<int:pk>/', CartUpdateAPIView.as_view()),
    path('API/delete/<int:pk>/', CartDeleteAPIView.as_view()),

    path('API/clean/<int:pk>/', CartCleanAPIView.as_view()),
    path('API/info/', CartInfoAPIView.as_view()),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Документация API",
        default_version='v1',
        description="Cервис SarafanStore",
        contact=openapi.Contact(email="bmgula55@mail.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [path('admin/', admin.site.urls),
               path('users/', include('users.urls', namespace='users')),
               path('cart/', include('cart.urls', namespace='cart')),
               path('', include('store.urls', namespace='store')),
               path('category/', include('product.urls', namespace='product')),

               path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
               path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from product.models import Product
from users.models import User

NULLABLE = {
    'blank': True,
    'null': True
}


class Cart(models.Model):
    '''Модель Корзины'''
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE)

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"


class CartProduct(models.Model):
    '''Модель Продукты корзины'''
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name='Корзина-Продукт', **NULLABLE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(verbose_name='Количество')
    release_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')

    def __str__(self):
        return str(self.product)

    def __repr__(self):
        return f'{self.__class__.__name__}({self.quantity})'

    class Meta:
        verbose_name = "Продукты корзины"
        verbose_name_plural = "Продукты корзины"
        ordering = ('release_date',)

cart/forms.py
from django import forms

from cart.models import CartProduct
from users.forms import StyleFormMixin


class CartForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = CartProduct
        exclude = ('release_date', )

templates/cart/cartproduct.html
{% extends 'store/base.html' %}


{% block content%}


<div class="container py-3">


    <form method="post" enctype="multipart/form-data">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title text-center">
                            {% if object.question%}
                            Редактированте продукта
                            {% else %}
                            Создание продукта
                            {% endif %}
                        </h2>
                    </div>

                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}


                    </div>

                    <div class="card-footer text-center">
                        {% if object.start_points_x%}
                        <button type="submit" class="col-6  btn btn-success">
                            <h5>Сохранить изменения</h5>
                        </button>
                        {% else %}
                        <button type="submit" class="col-6  btn btn-success">
                            <h5>Создать продукт</h5>
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


{% endblock %}

templates/cart/cartproduct_confirm_delete.html
{% extends 'store/base.html' %}}


{% block content%}
<div class="container  py-3">
    <div class="mb-5 ">
        <div class="text-center">

            <form method="post">
                {% csrf_token %}
                <H1>Вы хотите удалить вопрос?</H1>
                <br>
                <H4>ID:{{object.pk}} "{{object.question}}"</H4>
                <br>
                <button class="btn btn-outline-danger">Удалить</button>
                <a class="btn btn-outline-warning" href="{% url 'product:home' %}">Отмена</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/cart/cartproduct_detail.html
{% extends 'store/base.html' %}}


{% block content%}


<div class="container py-3">


    <div class="image-container row">
        <div class="col-12 pb-3">
            <H1>{{subcategory}}</H1>
        </div>

        {% for object in object_list %}
        <div class="col-4">


            <div class="height d-flex justify-content-center align-items-center">

                <div class="card p-3">

                    <div class="d-flex justify-content-between align-items-center ">
                        <div class="mt-2">
                            <h6 class="text-uppercase">{{object}}</h6>
                            <div class="mt-5">
                                <h5 class="text-uppercase mb-0">Стоимость</h5>
                                <h1 class="main-heading mt-0">{{object.price}} ₽</h1>

                            </div>
                        </div>
                        <div class="image">
                            {% if object.img %}
                            <img src="/media/{{object.img}}" width="200">
                            {% else %}
                            <img src="https://i.imgur.com/MGorDUi.png" width="200">
                            {% endif %}
                        </div>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mt-2 mb-2">
                        <span>{{object.subcategory}}</span>
                        <div class="colors">
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>

                    </div>


                    <p>{{object.subcategory.category}}</p>

                    <button class="btn btn-success">Добавить в корзину</button>
                </div>

            </div>
        </div>

        {% endfor %}
    </div>

    <div class="col-12 p-5">

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active" aria-current="page">
                    <span class="page-link">2</span>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</div>


<style>
    .image-container img {
               transition: transform 0.3s ease-in-out;
           }

    .image-container img:hover {
               transform: scale(1.2);
           }
</style>


{% endblock %}

templates/cart/cartproduct_list.html
{% extends 'store/base.html' %}}


{% block content%}

<section class="h-100 h-custom" style="background-color: #d2c9ff;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12">
                <div class="card card-registration card-registration-2" style="border-radius: 15px;">
                    <div class="card-body p-0">
                        <div class="row g-0">
                            <div class="col-lg-8">
                                <div class="p-5">
                                    <div class="d-flex justify-content-between align-items-center mb-5">
                                        <h1 class="fw-bold mb-0">Корзина покупок</h1>
                                        <h6 class="mb-0 text-muted">{{count}} кол-во</h6>
                                    </div>
                                    <hr class="my-4">
                                    {% for object in object_list %}
                                    {% if user.is_authenticated and user == object.user %}

                                    <div class="row mb-4 d-flex justify-content-between align-items-center">
                                        <div class="col-md-2 col-lg-2 col-xl-2">
                                            <img
                                                    src="/media/{{object.product.img}}"
                                                    class="img-fluid rounded-3" alt="Cotton T-shirt">
                                        </div>
                                        <div class="col-md-3 col-lg-3 col-xl-3">
                                            <h6 class="text-muted">{{object.product.subcategory}}</h6>
                                            <h6 class="mb-0">{{object.product}}</h6>
                                        </div>
                                        <div class="col-md-3 col-lg-3 col-xl-2 d-flex">

                                            <button data-mdb-button-init data-mdb-ripple-init class="btn btn-link px-2"
                                                    onclick="location.href='{% url 'cart:change_qty_cart' object.product_id %}'">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-dash" viewBox="0 0 16 16">
                                                    <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8"/>
                                                </svg>
                                            </button>

                                            <input id="form1" min="1" name="quantity" value="{{object.quantity}}"
                                                   class="form-control form-control-sm"/>

                                            <button data-mdb-button-init data-mdb-ripple-init class="btn btn-link px-2"
                                                    onclick="location.href='{% url 'cart:product_add_cart' object.product_id %}'">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                                                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                                                </svg>
                                            </button>


                                        </div>
                                        <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                            <h6 class="mb-0">{{object.product.price}} ₽</h6>
                                        </div>

                                        <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                            <a href="{% url 'cart:product_delete_cart' object.product.pk %}"
                                               class="text-muted">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd"
                                                          d="M13.854 2.146a.5.5 0 0 1 0 .708l-11 11a.5.5 0 0 1-.708-.708l11-11a.5.5 0 0 1 .708 0Z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M2.146 2.146a.5.5 0 0 0 0 .708l11 11a.5.5 0 0 0 .708-.708l-11-11a.5.5 0 0 0-.708 0Z"/>
                                                </svg>
                                            </a>
                                        </div>
                                    </div>

                                    <hr class="my-3">

                                    {% endif %}
                                    {% endfor %}
                                    {% if count != 0 %}
                                    <a class="btn btn-outline-danger float-end"
                                       href="{% url 'cart:clean_cart' %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                            <path fill-rule="evenodd"
                                                  d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                        </svg>
                                        Очистить
                                    </a>
                                    {% endif %}

                                </div>
                            </div>
                            <div class="col-lg-4 bg-body-tertiary">
                                <div class="p-5">
                                    <h3 class="fw-bold mb-5 mt-2 pt-1">Итого:</h3>
                                    <hr class="my-4">


                                    <div class="d-flex justify-content-between mb-4">
                                        <h5 class="text-uppercase">Всего: {{all_count}}</h5>
                                        <h5>{{all_price}} ₽</h5>
                                    </div>

                                    <h5 class="text-uppercase mb-3">Доставка</h5>

                                    <div class="mb-4 pb-2">
                                        <select data-mdb-select-init>
                                            <option value="1">Бесплатная 0 ₽</option>
                                        </select>
                                    </div>

                                    <h5 class="text-uppercase mb-3">Использовать промокод</h5>

                                    <div class="mb-5">
                                        <div data-mdb-input-init class="form-outline">
                                            <input type="text" id="form3Examplea2"
                                                   class="form-control form-control-lg"/>
                                            <label class="form-label" for="form3Examplea2">Введите свой код</label>
                                        </div>
                                    </div>

                                    <hr class="my-4">

                                    <div class="d-flex justify-content-between mb-5">
                                        <h5 class="text-uppercase">Итоговая цена:</h5>
                                        <h5>{{all_price}} ₽</h5>
                                    </div>

                                    <button type="button" data-mdb-button-init data-mdb-ripple-init
                                            class="btn btn-dark btn-block btn-lg"
                                            data-mdb-ripple-color="dark">Оформить заказ
                                    </button>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}