cart/urls.py
from django.urls import path

from cart.apps import CartConfig
from cart.view.API_cart import CartListAPIView, CartCreateAPIView, CartDeleteAPIView, CartUpdateAPIView, \
    CartCleanAPIView, CartInfoAPIView
from cart.view.cart import CartListView, product_add_cart, change_qty_cart, clean_cart, product_delete_cart

app_name = CartConfig.name

urlpatterns = [
    # Cart
    path('', CartListView.as_view(), name='home'),
    path('create/<int:pk>/', product_add_cart, name='product_add_cart'),
    path('change/<int:pk>/', change_qty_cart, name='change_qty_cart'),
    path('clean/', clean_cart, name='clean_cart'),
    path('delete/<int:pk>/', product_delete_cart, name='product_delete_cart'),

    # API Cart
    path('API/', CartListAPIView.as_view()),
    path('API/create/', CartCreateAPIView.as_view()),
    path('API/update/<int:pk>/', CartUpdateAPIView.as_view()),
    path('API/delete/<int:pk>/', CartDeleteAPIView.as_view()),

    path('API/clean/<int:pk>/', CartCleanAPIView.as_view()),
    path('API/info/', CartInfoAPIView.as_view()),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Документация API",
        default_version='v1',
        description="Cервис SarafanStore",
        contact=openapi.Contact(email="bmgula55@mail.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [path('admin/', admin.site.urls),
               path('users/', include('users.urls', namespace='users')),
               path('cart/', include('cart.urls', namespace='cart')),
               path('', include('store.urls', namespace='store')),
               path('category/', include('product.urls', namespace='product')),

               path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
               path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from product.view.API_product import ProductListAPIView, ProductDetailAPIView, ProductCreateAPIView, \
    ProductUpdateAPIView, ProductDeleteAPIView, CategoryListAPIView
from product.views import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, CategoryListView, \
    CategoryCreateView, CategoryUpdateView, ProductDetailView, CategoryDetailView
from product.apps import ProductConfig

app_name = ProductConfig.name

urlpatterns = [
    # Category
    path('', CategoryListView.as_view(), name='category_home'),
    path('<slug>', CategoryDetailView.as_view(), name='category_view'),
    path('create/', CategoryCreateView.as_view(), name='category_create'),
    path('update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),

    # Product
    path('product/', ProductListView.as_view(), name='home'),
    path('<int:pk>/', ProductDetailView.as_view(), name='view'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),

    # API Product
    path('API/', ProductListAPIView.as_view()),
    path('API/<int:pk>/', ProductDetailAPIView.as_view()),
    path('API/create/', ProductCreateAPIView.as_view()),
    path('API/update/<int:pk>/', ProductUpdateAPIView.as_view()),
    path('API/delete/<int:pk>/', ProductDeleteAPIView.as_view()),

    # API Category
    path('API/category/', CategoryListAPIView.as_view()),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    # Авторизации и регистрации
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # Token
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

product/models.py
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe

from store.services import unique_slugify
from users.models import User

NULLABLE = {
    'blank': True,
    'null': True
}


class Category(models.Model):
    '''Модель Категории'''
    title = models.CharField(max_length=300, verbose_name='Название')
    slug = models.CharField(verbose_name='Альт.название', max_length=255, blank=True, unique=True)
    img = models.ImageField(upload_to='category', verbose_name='Изображение', **NULLABLE)

    release_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор продукта', **NULLABLE)

    def __str__(self):
        return self.title

    def __repr__(self):
        return f'{self.__class__.__name__}({self.title})'

    def save(self, *args, **kwargs):
        """Сохранение полей модели при их отсутствии заполнения"""
        if not self.slug:
            self.slug = unique_slugify(self, self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        # ordering = ('title',)


class Subcategory(models.Model):
    '''Модель Подкатегории'''
    title = models.CharField(max_length=300, verbose_name='Название')
    slug = models.CharField(verbose_name='Альт.название', max_length=255, blank=True, unique=True)
    img = models.ImageField(upload_to='subcategory', verbose_name='Изображение', **NULLABLE)

    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    release_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор продукта', **NULLABLE)

    def __str__(self):
        return self.title

    def __repr__(self):
        return f'{self.__class__.__name__}({self.title})'

    def save(self, *args, **kwargs):
        """
        Сохранение полей модели при их отсутствии заполнения
        """
        if not self.slug:
            self.slug = unique_slugify(self, self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'
        # ordering = ('title',)


class Product(models.Model):
    '''Модель продукта'''
    title = models.CharField(max_length=300, verbose_name='Название')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    slug = models.CharField(verbose_name='Альт.название', max_length=255, blank=True, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=3, verbose_name='Цена')
    img = models.ImageField(upload_to='product', verbose_name='Изображение', **NULLABLE)

    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, verbose_name='Подкатегория')

    release_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор продукта', **NULLABLE)

    def __str__(self):
        return self.title

    def __repr__(self):
        return f'{self.__class__.__name__}({self.title})'

    def save(self, *args, **kwargs):
        """
        Сохранение полей модели при их отсутствии заполнения
        """
        if not self.slug:
            self.slug = unique_slugify(self, self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('title',)


class ProductImageInline(models.Model):
    '''Модель картинок к продукту'''
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    img = models.ImageField(upload_to='product', verbose_name='Изображение', **NULLABLE)

    def __str__(self):
        return str(self.img)

    class Meta:
        verbose_name = 'Картинка'
        verbose_name_plural = 'Картинки'

product/forms.py
from django import forms

from product.models import Category
from users.forms import StyleFormMixin


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Category
        exclude = ('release_date', 'author',)

        widgets = {
            'price': forms.NumberInput(
                attrs={
                    'min': 1,
                }),
        }

product/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import paginator
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.views.generic.list import MultipleObjectMixin

from cart.models import Cart, CartProduct
from product.forms import ProductForm
from product.models import Product, Category, Subcategory


class ProductDetailView(DetailView):
    """Класс просмотра 1 продукта"""
    model = Product

    # paginate_by = 1

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        if user.is_authenticated:
            context['count'] = Cart.objects.filter(user=user).count()
        category_pk = context.get('object').pk
        context['object_list'] = Product.objects.filter(subcategory=category_pk)
        context['subcategory'] = Subcategory.objects.filter(pk=category_pk).first()

        return context


class ProductListView(ListView):
    """Класс отображения продукта"""
    model = Product

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        user = self.request.user

        if user.is_authenticated:
            context['count'] = CartProduct.objects.filter(user=user).count()

        search_query = self.request.GET.get('search_query')
        if search_query:
            res = Product.objects.filter(title__icontains=str(search_query).strip())
            context['object_list'] = res
            context['search_query'] = self.request.GET.get('search_query')
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    """Класс создания продукта"""
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('product:home')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    """Класс редактирования продукта"""
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('product:home')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        return form


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """Класс удаления продукта"""
    model = Product
    success_url = reverse_lazy('product:home')


class CategoryDetailView(DetailView):
    """Класс просмотра 1 категории"""
    model = Category

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['Subcategory'] = Subcategory.objects.all()

        user = self.request.user
        if user.is_authenticated:
            context['count'] = CartProduct.objects.filter(user=user).count()

        category_slug = context.get('object').slug
        res = Subcategory.objects.filter(category__slug=category_slug)
        result = [Product.objects.filter(subcategory=item) for item in res if Product.objects.filter(subcategory=item)]
        context['object_list'] = result

        return context


class CategoryListView(ListView):
    """Класс отображения категории"""
    model = Category

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['Subcategory'] = Subcategory.objects.all()
        user = self.request.user

        if user.is_authenticated:
            context['count'] = CartProduct.objects.filter(user=user).count()

        search_query = self.request.GET.get('search_query')
        if search_query:
            res = Product.objects.filter(title__icontains=str(search_query).strip())
            context['object_list'] = res
            context['search_query'] = self.request.GET.get('search_query')

        return context


class CategoryCreateView(LoginRequiredMixin, CreateView):
    """Класс создания категории"""
    model = Category
    form_class = ProductForm
    success_url = reverse_lazy('store:home')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    """Класс редактирования категории"""
    model = Category
    form_class = ProductForm
    success_url = reverse_lazy('store:home')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        return form


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    """Класс удаления категории"""
    model = Category
    success_url = reverse_lazy('store:home')

templates/product/category_detail.html
{% extends 'store/base.html' %}}


{% block content%}


<div class="container py-3">


    <div class="image-container row">

        {% for object1 in object_list %}

        <div class="image-container row">
            <div class="col-12 pb-3 card" style="background: #ffc107;">
                <H1>{{object1.first.subcategory}}</H1>
            </div>
            {% for object in object1 %}
            <div class="col-4 p-2">
                <div class="height d-flex justify-content-center align-items-center">

                    <div class="card p-3 m-1">

                        <div class="d-flex justify-content-between align-items-center ">
                            <div class="mt-2">
                                <h6 class="text-uppercase">{{object}}</h6>
                                <div class="mt-5">
                                    <h5 class="text-uppercase mb-0">Стоимость</h5>
                                    <h1 class="main-heading mt-0">{{object.price}} ₽</h1>

                                </div>
                            </div>
                            <div class="image">
                                {% if object.img %}
                                <img src="/media/{{object.img}}" width="200">
                                {% else %}
                                <img src="https://i.imgur.com/MGorDUi.png" width="200">
                                {% endif %}
                            </div>
                        </div>

                        <div class="d-flex justify-content-between align-items-center mt-2 mb-2">
                            <span>{{object.subcategory}}</span>
                            <div class="colors">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </div>


                        <p>{{object.subcategory.category}}</p>

                        {% if user.is_authenticated %}
                        <a href="{%url 'cart:product_add_cart' object.pk %}">
                            <button class="btn btn-success">Добавить в корзину</button>
                        </a>
                        {% else %}
                        <a href="{%url 'users:login'%}">
                            <button class="btn btn-success">Добавить в корзину</button>
                        </a>
                        {% endif %}
                    </div>

                </div>
            </div>
            {% endfor %}
        </div>

        {% endfor %}

        <div class="col-12 p-5">

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <span class="page-link">Previous</span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active" aria-current="page">
                        <span class="page-link">2</span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>


<style>
    .image-container img {
               transition: transform 0.3s ease-in-out;
           }

    .image-container img:hover {
               transform: scale(1.2);
           }
</style>


{% endblock %}

templates/product/category_form.html
{% extends 'store/base.html' %}


{% block content%}


<div class="container py-3">


    <form method="post" enctype="multipart/form-data">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title text-center">
                            {% if object.question%}
                            Редактированте продукта
                            {% else %}
                            Создание продукта
                            {% endif %}
                        </h2>
                    </div>

                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}


                    </div>

                    <div class="card-footer text-center">
                        {% if object.start_points_x%}
                        <button type="submit" class="col-6  btn btn-success">
                            <h5>Сохранить изменения</h5>
                        </button>
                        {% else %}
                        <button type="submit" class="col-6  btn btn-success">
                            <h5>Создать продукт</h5>
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


{% endblock %}

templates/product/category_list.html
{% extends 'store/base.html' %}}


{% block content%}


<div class="container py-3">

    <div class="row align-items-start">
        <div class="col-3 border-start border-end">
            <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                {% for object in object_list %}


                <div class="col-12 p-2">
                    <a class="btn btn-light col-12 text-center p-2"
                       style="border: 2px solid black; background: #198754;"
                       data-bs-toggle="collapse"
                       href="#collapseExample{{object.pk}}"
                       role="button"
                       aria-expanded="false"
                       aria-controls="collapseExample"><h6>{{object}}</h6></a>
                </div>

                <div class="collapse pt-2" id="collapseExample{{object.pk}}">
                    {% for item in Subcategory%}
                    {% if item.category == object %}
                    <div class="row justify-content-center m-1">
                        <div class="text-center col-11">
                            <div class="list-group">
                                <a href="{% url 'product:view' item.pk %}"
                                   class="p-2 mx-3 btn btn-outline-success text-decoration-none text-reset"
                                   aria-current="true">
                                    {{item}}
                                </a>
                            </div>

                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>

                {% endfor %}
            </div>
        </div>


        <div class="col-9">
            <div class="tab-content" id="v-pills-tabContent">
                <div class="row">


                    {% for object in object_list %}
                        <div class="col-4 p-2">
                            <a class="p-2 mx-3 btn btn-outline-success text-decoration-none text-reset"
                               href="{% url 'product:category_view' object.slug %}">
                                <div class="image-container card">
                                    <img class="card-img-top p-1 " src="/media/{{object.img}}"
                                         style="width:100%; height:auto">
                                    <div class="card-footer">
                                        <h5 class="card-title text-center">{{object}}</h5>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
</div>


<style>
    .image-container img {
               transition: transform 0.3s ease-in-out;
           }

    .image-container img:hover {
               transform: scale(1.1);
           }

    .image-container .card-footer {
                background:#ffc107
           }


</style>


{% endblock %}

templates/product/product_confirm_delete.html
{% extends 'store/base.html' %}}


{% block content%}
<div class="container  py-3">
    <div class="mb-5 ">
        <div class="text-center">

            <form method="post">
                {% csrf_token %}
                <H1>Вы хотите удалить вопрос?</H1>
                <br>
                <H4>ID:{{object.pk}} "{{object.question}}"</H4>
                <br>
                <button class="btn btn-outline-danger">Удалить</button>
                <a class="btn btn-outline-warning" href="{% url 'product:home' %}">Отмена</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/product/product_detail.html
{% extends 'store/base.html' %}}


{% block content%}


<div class="container py-3">


    <div class="image-container row">
        <div class="col-12 pb-3 card" style="background: #ffc107;">
            <H1>{{subcategory}}</H1>
        </div>

        {% for object in object_list %}
        <div class="col-4 p-2">


            <div class="height d-flex justify-content-center align-items-center">

                <div class="card p-3">

                    <div class="d-flex justify-content-between align-items-center ">
                        <div class="mt-2">
                            <h6 class="text-uppercase">{{object}}</h6>
                            <div class="mt-5">
                                <h5 class="text-uppercase mb-0">Стоимость</h5>
                                <h1 class="main-heading mt-0">{{object.price}} ₽</h1>

                            </div>
                        </div>
                        <div class="image">
                            {% if object.img %}
                            <img src="/media/{{object.img}}" width="200">
                            {% else %}
                            <img src="https://i.imgur.com/MGorDUi.png" width="200">
                            {% endif %}
                        </div>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mt-2 mb-2">
                        <span>{{object.subcategory}}</span>
                        <div class="colors">
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>

                    <p>{{object.subcategory.category}}</p>

                    {% if user.is_authenticated %}
                    <a href="{%url 'cart:product_add_cart' object.pk %}">
                        <button class="btn btn-success">Добавить в корзину</button>
                    </a>
                    {% else %}
                    <a href="{%url 'users:login'%}">
                        <button class="btn btn-success">Добавить в корзину</button>
                    </a>
                    {% endif %}
                </div>

            </div>
        </div>

        {% endfor %}
    </div>

    <div class="col-12 p-5">

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active" aria-current="page">
                    <span class="page-link">2</span>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</div>


<style>
    .image-container img {
               transition: transform 0.3s ease-in-out;
           }

    .image-container img:hover {
               transform: scale(1.2);
           }
</style>


{% endblock %}

templates/product/product_form.html
{% extends 'store/base.html' %}


{% block content%}


<div class="container py-3">


    <form method="post" enctype="multipart/form-data">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-title text-center">
                            {% if object.question%}
                            Редактированте продукта
                            {% else %}
                            Создание продукта
                            {% endif %}
                        </h2>
                    </div>

                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}


                    </div>

                    <div class="card-footer text-center">
                        {% if object.start_points_x%}
                        <button type="submit" class="col-6  btn btn-success">
                            <h5>Сохранить изменения</h5>
                        </button>
                        {% else %}
                        <button type="submit" class="col-6  btn btn-success">
                            <h5>Создать продукт</h5>
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>


{% endblock %}

templates/product/product_list.html
{% extends 'store/base.html' %}}


{% block content%}


<div class="container py-3">


    <div class="image-container row">
        <div class="col-12 pb-3">
            <H1>{{subcategory}}</H1>
        </div>

        {% for object in object_list %}
        <div class="col-4">


            <div class="height d-flex justify-content-center align-items-center">

                <div class="card p-3">

                    <div class="d-flex justify-content-between align-items-center ">
                        <div class="mt-2">
                            <h6 class="text-uppercase">{{object}}</h6>
                            <div class="mt-5">
                                <h5 class="text-uppercase mb-0">Стоимость</h5>
                                <h1 class="main-heading mt-0">{{object.price}} ₽</h1>

                            </div>
                        </div>
                        <div class="image">
                            {% if object.img %}
                            <img src="/media/{{object.img}}" width="200">
                            {% else %}
                            <img src="https://i.imgur.com/MGorDUi.png" width="200">
                            {% endif %}
                        </div>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mt-2 mb-2">
                        <span>{{object.subcategory}}</span>
                        <div class="colors">
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>

                    </div>


                    <p>{{object.subcategory.category}}</p>

                    <button class="btn btn-success">Добавить в корзину</button>
                </div>

            </div>
        </div>

        {% endfor %}
    </div>

    <div class="col-12 p-5">

        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active" aria-current="page">
                    <span class="page-link">2</span>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>

</div>


<style>
    .image-container img {
               transition: transform 0.3s ease-in-out;
           }

    .image-container img:hover {
               transform: scale(1.2);
           }
</style>


{% endblock %}