cart/urls.py
from django.urls import path

from cart.apps import CartConfig
from cart.view.API_cart import CartListAPIView, CartCreateAPIView, CartDeleteAPIView, CartUpdateAPIView, \
    CartCleanAPIView, CartInfoAPIView
from cart.view.cart import CartListView, product_add_cart, change_qty_cart, clean_cart, product_delete_cart

app_name = CartConfig.name

urlpatterns = [
    # Cart
    path('', CartListView.as_view(), name='home'),
    path('create/<int:pk>/', product_add_cart, name='product_add_cart'),
    path('change/<int:pk>/', change_qty_cart, name='change_qty_cart'),
    path('clean/', clean_cart, name='clean_cart'),
    path('delete/<int:pk>/', product_delete_cart, name='product_delete_cart'),

    # API Cart
    path('API/', CartListAPIView.as_view()),
    path('API/create/', CartCreateAPIView.as_view()),
    path('API/update/<int:pk>/', CartUpdateAPIView.as_view()),
    path('API/delete/<int:pk>/', CartDeleteAPIView.as_view()),

    path('API/clean/<int:pk>/', CartCleanAPIView.as_view()),
    path('API/info/', CartInfoAPIView.as_view()),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Документация API",
        default_version='v1',
        description="Cервис SarafanStore",
        contact=openapi.Contact(email="bmgula55@mail.ru"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [path('admin/', admin.site.urls),
               path('users/', include('users.urls', namespace='users')),
               path('cart/', include('cart.urls', namespace='cart')),
               path('', include('store.urls', namespace='store')),
               path('category/', include('product.urls', namespace='product')),

               path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
               path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from product.view.API_product import ProductListAPIView, ProductDetailAPIView, ProductCreateAPIView, \
    ProductUpdateAPIView, ProductDeleteAPIView, CategoryListAPIView
from product.views import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, CategoryListView, \
    CategoryCreateView, CategoryUpdateView, ProductDetailView, CategoryDetailView
from product.apps import ProductConfig

app_name = ProductConfig.name

urlpatterns = [
    # Category
    path('', CategoryListView.as_view(), name='category_home'),
    path('<slug>', CategoryDetailView.as_view(), name='category_view'),
    path('create/', CategoryCreateView.as_view(), name='category_create'),
    path('update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),

    # Product
    path('product/', ProductListView.as_view(), name='home'),
    path('<int:pk>/', ProductDetailView.as_view(), name='view'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),

    # API Product
    path('API/', ProductListAPIView.as_view()),
    path('API/<int:pk>/', ProductDetailAPIView.as_view()),
    path('API/create/', ProductCreateAPIView.as_view()),
    path('API/update/<int:pk>/', ProductUpdateAPIView.as_view()),
    path('API/delete/<int:pk>/', ProductDeleteAPIView.as_view()),

    # API Category
    path('API/category/', CategoryListAPIView.as_view()),

]

store/urls.py
from django.urls import path

from store.apps import StoreConfig
from store.views import view_home

app_name = StoreConfig.name

urlpatterns = [
    path('', view_home, name='home'),

]

store/views.py
from django.shortcuts import render

from cart.models import Cart, CartProduct


def view_home(request):
    user = request.user
    count = 0
    if user.is_authenticated:
        count = CartProduct.objects.filter(user=user).count()
    return render(request, 'store/home.html', {'count': count})

templates/store/base.html
{% include 'store/includes/inc_catalog_menu.html' %}
{% load static %}

<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ title }}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<body class="m-0 p-0">

<div class="py-2"></div>

<div class="container py-3">
    <div class="container px-4 pb-2" id="hanging-icons">
        <div class="row mb-4 border-bottom">
            <div class="col-3 text-center">
                <a class="px-5 btn btn-warning" href="{% url 'product:category_home' %}">Каталог</a>
            </div>

            <div class="col-9 text-center">
                <form class="d-flex mb-3" role="search" method="get" action="">
                    <input type="text" name="search_query" class="form-control me-2" placeholder="Искать в Сарафане"
                           aria-label="Search" id="id_search_query"
                           value="{% if search_query%}{{search_query}}{% endif %}">
                    <button class="btn btn-outline-success" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% block content%}


{% endblock %}


<footer class="pt-4 my-md-5 pt-md-5 border-top ">
    <div class="row p-0 m-0">
        <div class="col-1 col-md"></div>
        <div class="col-3 col-md">
            Сарафан
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-2 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-2 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-2 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li>
                    <a class="text-muted" href="#">
                        Контакты
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>

<script src="/static/js/bootstrap.bundle.min.js"></script>


</body>
</html>

templates/store/home.html
{% extends 'store/base.html' %}}


{% block content%}

<div class="container py-3">
    <div class="row justify-content-center">
        <div class="col-4 border p-2 m-2 text-center">
            <img src="/media/store/1.jpg" width="100%">
        </div>
        <div class="col-3 border p-2 m-2 text-center">
            <img src="/media/store/2.jpg" width="100%">
        </div>
        <div class="col-4 border p-2 m-2 text-center">
            <img src="/media/store/3.jpg" width="100%">
        </div>
    </div>

    <h3 class="m-5">Как мы работаем</h3>

    <div class="row justify-content-center">
        <div class="col-4 border p-2 m-2 text-center">
            <img src="/media/store/4.png" width="100%">
            <p>Выберите продукты в каталоге, мы покажем вам самые выгодные предложения</p>
        </div>
        <div class="col-3 border p-2 m-2 text-center">
            <img src="/media/store/5.png" width="100%">
            <br>
            <br>
            
            <p class="my-5">Выберите продукты в каталоге, мы покажем вам самые выгодные предложения</p>
        </div>
        <div class="col-4 border p-2 m-2 text-center">
            <img src="/media/store/6.png" width="100%">
            <p>Выберите продукты в каталоге, мы покажем вам самые выгодные предложения</p>
        </div>
    </div>

</div>

{% endblock %}